from settings import *

#####################################

# colours 

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

BACKGROUND_COLOUR = (3, 29, 69)
BUTTON_ALIVE_COLOUR = (0, 166, 255)
BUTTON_DEAD_COLOUR = (41, 60, 89)
BUTTON_HINT_COLOUR = (217, 106, 106)

HINT_BUTTON_COLOUR = (5, 54, 94)

GAMEOVER_INCORRECT_COLOUR = (235, 5, 5)
GAMEOVER_CORRECT_COLOUR = (235, 201, 52)

#####################################

# screen configuration variables

SCREEN_WIDTH = 1280 
SCREEN_HEIGHT = 720


#####################################

# button variables 

BUTTON_WIDTH = 291
BUTTON_HEIGHT = 65

BUTTON_COLOURS = (BUTTON_ALIVE_COLOUR, BUTTON_DEAD_COLOUR, BUTTON_HINT_COLOUR) # alive, dead, help mode

BUTTON_TEXTFONT = 'HELVETICA'
BUTTON_TEXTCOLOUR = BLACK

BUTTON_FONTSIZE = 25


# panel configurations variables

ROWS = int(N_MANY / 4)
COLUMNS = 4

PANEL_X = 40
PANEL_Y = 40
H_SPACE = 12
V_SPACE = 12

#####################################

# logbook variables

LOGBOOK_X = 40
LOGBOOK_Y = 480
LOGBOOK_WIDTH = 897
LOGBOOK_HEIGHT = 200 
LOGBOOK_BACKGROUND = WHITE
LOGBOOK_FRAMECOLOUR = BLACK
LOGBOOK_FRAMESIZE = 3

LOGBOOK_TEXTFONT = 'HELVETICA'
LOGBOOK_TEXTCOLOUR = BLACK
LOGBOOK_FONTSIZE = 25


#####################################

# inputbox variables

INPUTBOX_X = 40
INPUTBOX_Y = 435
INPUTBOX_WIDTH = 220
INPUTBOX_HEIGHT = 40
INPUTBOX_BACKGROUND = WHITE
INPUTBOX_FRAMECOLOUR = BLACK
INPUTBOX_FRAMESIZE = 2

INPUTBOX_TEXTFONT = 'HELVETICA'
INPUTBOX_TEXTCOLOUR = BLACK
INPUTBOX_FONTSIZE = 22

INPUTBOX_INITIALTEXT = 'Click here to write!'

INPUTBOX_CURSORWIDTH = 2


#####################################

# hint button variables

HINT_BUTTON_X = 994
HINT_BUTTON_Y = 500
HINT_BUTTON_WIDTH = 200
HINT_BUTTON_HEIGHT = 40 
HINT_BUTTON_COLOUR = HINT_BUTTON_COLOUR

HINT_BUTTON_TEXTFONT = 'HELVETICA'
HINT_BUTTON_TEXTCOLOUR = BLACK
HINT_BUTTON_FONTSIZE = 25


#####################################

# guess button variables

GUESS_BUTTON_X = 994
GUESS_BUTTON_Y = 550
GUESS_BUTTON_WIDTH = 200
GUESS_BUTTON_HEIGHT = 110
GUESS_BUTTON_COLOUR = HINT_BUTTON_COLOUR

#####################################

# game over menu variables 

GAMEOVER_WIDTH = 640 
GAMEOVER_HEIGHT = 360 
GAMEOVER_COLOURS = (GAMEOVER_CORRECT_COLOUR, GAMEOVER_INCORRECT_COLOUR)

GAMEOVER_TEXTFONT = 'ARIAL'
GAMEOVER_TEXTFONT_GO = 'ARIAL'
GAMEOVER_TEXTCOLOUR = WHITE
GAMEOVER_FONTSIZE = 45
GAMEOVER_FONTSIZE_GO = 25

#####################################